# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Author: jaerveli
# Date: 22 March 2013
# Description:
#      A simple script to make a plot out of summary numbers generated by getPerformace.R (summaryOut)
#
# cat /g/steinmetz/project/mTEC_Seq/src/estimateSaturation.R | R --slave --args
#	inDir='/g/steinmetz/project/mTEC_Seq/run/5TSeq_mTec1_2014-03-18_C3V0VACXX/collapsing/'
#	outDir='/g/steinmetz/project/mTEC_Seq/run/5TSeq_mTec1_2014-03-18_C3V0VACXX/performance/'
#	inPattern='_countsPerMol.tsv'
#	outPdf='Simulation_coverage-to-identified-5-ends_all-data'
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


library(RColorBrewer)
options(scipen=20)


#### PROCESS THE INPUT ARGUMENTS

args = commandArgs(TRUE);

if(length(args)==0){
        stop("No arguments provided!\n")
} else {
        inDir =ifelse( length(grep('inDir', args) )>0, strsplit(args[grep('inDir', args)], '=')[[1]][2], stop('No inDir argument provided!'))
        outDir =ifelse( length(grep('outDir', args) )>0, strsplit(args[grep('outDir', args)], '=')[[1]][2], stop('No outDir argument provided!'))
        inPattern =ifelse( length(grep('inPattern', args) )>0, strsplit(args[grep('inPattern', args)], '=')[[1]][2], stop('No inPattern argument provided!'))
        outPdf =ifelse( length(grep('outPdf', args) )>0, strsplit(args[grep('outPdf', args)], '=')[[1]][2], stop('No outPdf argument provided!'))
}

###### A FEW FIXED PARAMETERS

sampleSizes = c(50000, 100000, 200000, 500000, 1000000, 2000000, 3000000, 4000000, 5000000)
repeats = 100
genomic=c( '1','10','11','12','13','14','15','16','17','18','19','2','3','4','5','6','7','8','9', '20', '21', '22','X','Y' )



###### FUNCTIONS

## A helper function to sample positions
estimateSaturation = function(myT=myT, sampleSizes=sampleSizes, repeats=repeats) {

	positions = apply(myT[, 1:3], 1, paste, collapse="_")
	posPerSample=NULL
	for( s in sampleSizes) {
		cat( paste('Sampling size ', s, '...\n', sep=''))
		if(s > length(myT[,1])) {
			x=NA
			names(x)=as.character(s)
			posPerSample = append(posPerSample, x)
		} else {
			myList = list()
			for(r in 1:repeats) {
				myList=append(myList, length(unique(sample(positions,s))) )
			}
			x = mean(unlist(myList))
			names(x)=as.character(s)
			posPerSample = append(posPerSample, x)
		}
	}
	return(posPerSample)
}


###### PLOT

myFiles = list.files(path=inDir, pattern=inPattern)
myColors=brewer.pal(length(myFiles), "Set3")


## Sample each sampleSize 100 times and get mean/median number of positions

st=as.data.frame(matrix(nrow=length(myFiles),ncol=length(sampleSizes)))
rownames(st) = do.call(cbind, strsplit(myFiles, '_'))[1,]
colnames(st) = sampleSizes

for(f in myFiles) {
	cat( paste('Processing file ', f, '\n',sep=''))
	myT = read.delim(paste(inDir,f,sep=''))
	myT = myT[which(myT$chr %in% genomic),]
	sat = estimateSaturation(myT=myT, sampleSizes=sampleSizes, repeats=repeats)
	st[strsplit(f, '_')[[1]][1], ] = sat
	cat('\n')
}


pdf(paste(outDir, outPdf, sep=''))
plot(NA, xlim=c(0, max(sampleSizes)), ylim=c(0, max(st, na.rm=T)), main="Simulation:\nHow many unique 5' positions identified with increasing coverage", xlab='Number of molecules', ylab='Number of positions')
for(c in 1:length(st[,1])) {
	lines(as.integer(colnames(st)), st[c,], col=myColors[c], type="b", lwd=2)
}
legend("topleft", legend=rownames(st), fill=myColors)
legend("bottomright", legend=paste('Repeats per sampling point:', as.character(repeats)), bty="n" )
dev.off()



