# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Author: jaerveli
# Date: 21 March 2013
# Description:
#      A simple script to make a plot out of summary numbers generated by getPerformace.R (summaryOut)
#
# cat /g/steinmetz/project/mTEC_Seq/src/plotEfficiency.R | R --slave --args
#	dir='/g/steinmetz/project/mTEC_Seq/run/5TSeq_mTec1_2014-03-18_C3V0VACXX/performance/'
#	infile='summary.tsv'
#	outPdf='mTEC_5Seq_yield.pdf'
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


options(scipen=20)


#### PROCESS THE INPUT ARGUMENTS

args = commandArgs(TRUE);

if(length(args)==0){
        stop("No arguments provided!\n")
} else {
        dir =ifelse( length(grep('indir', args) )>0, strsplit(args[grep('indir', args)], '=')[[1]][2], stop('No indir argument provided!'))
        infile =ifelse( length(grep('infile', args) )>0, strsplit(args[grep('infile', args)], '=')[[1]][2], stop('No infile argument provided!'))
        outPdf =ifelse( length(grep('outPdf', args) )>0, strsplit(args[grep('outPdf', args)], '=')[[1]][2], stop('No outPdf argument provided!'))
}

options(scipen=20)

library("reshape2", lib.loc="/g/steinmetz/jaerveli/bin/R/")
library("ggplot2", lib.loc="/g/steinmetz/jaerveli/bin/R/")

t2=read.delim(paste(dir, infile, sep=''))

tEff = as.data.frame( matrix( nrow=length(rownames(t2))*4, ncol=0 ) )
tEff$Sample = rep( 1:4, length(rownames(t2)))
tEff$Group = rep(rownames(t2), each=4)
tEff$Step = rep( c('1: Total','2: Aligned (unique)', '3: Molecules', '4: Positions'), length(rownames(t2)))
tEff$Reads = as.integer(c(t(t2))) # as.integer(c( t2[1,], t2[2,], t2[3,], t2[4,] ))

pdf(paste(dir, outPdf,sep=''))
ggplot() +
  geom_bar(data=tEff, aes(y = Reads, x = Sample, fill = Step), stat="identity",
           position='stack') +
  theme_bw() + 
  facet_grid( ~ Group) + labs(title="5Seq yields")
dev.off()

