# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# Author: jaerveli
# Date: 21 March 2013
# Description:
#      A simple script to make a plot out of summary numbers generated by getPerformace.R (summaryOut)
#
# cat /g/steinmetz/project/mTEC_Seq/src/plotPCRamplification.R | R --slave --args
#       inDir='/g/steinmetz/project/mTEC_Seq/run/5TSeq_mTec1_2014-03-18_C3V0VACXX/collapsing/'
#       outDir='/g/steinmetz/project/mTEC_Seq/run/5TSeq_mTec1_2014-03-18_C3V0VACXX/performance/'
#       inPattern='_countsPerMol.tsv'
#       outPdf='PCR_amplification.pdf'
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #


#### PROCESS THE INPUT ARGUMENTS

args = commandArgs(TRUE);

if(length(args)==0){
        stop("No arguments provided!\n")
} else {
        inDir =ifelse( length(grep('inDir', args) )>0, strsplit(args[grep('inDir', args)], '=')[[1]][2], stop('No inDir argument provided!'))
        outDir =ifelse( length(grep('outDir', args) )>0, strsplit(args[grep('outDir', args)], '=')[[1]][2], stop('No outDir argument provided!'))
        inPattern =ifelse( length(grep('inPattern', args) )>0, strsplit(args[grep('inPattern', args)], '=')[[1]][2], stop('No inPattern argument provided!'))
        outPdf =ifelse( length(grep('outPdf', args) )>0, strsplit(args[grep('outPdf', args)], '=')[[1]][2], stop('No outPdf argument provided!'))
}


#myFiles=paste(inDir, list.files(path=inDir, pattern=inPattern), sep='')
myFiles=list.files(path=inDir, pattern=inPattern)

#print(myFiles)

pdf(paste(outDir, outPdf, sep=''), width=10, height=10)
par(mfrow=c(length(myFiles)/2,2))
for( f in myFiles) {
        myT = read.delim(paste(inDir,f,sep=''))
        plot( as.integer(names(table(myT$count))), as.integer(table(myT$count)), type='h', xlim=c(0,100), xlab='Number of times present', ylab='Unique molecules', main=paste(strsplit(f, "_")[[1]][1], "PCR amplification"))
        legend('topright', legend=paste( names(quantile(myT$count, probs = seq(0, 1, 0.10))), as.character( quantile(myT$count, probs = seq(0, 1, 0.10))),sep='\t'))
}
#dev.off()


### ecdf type of a plot

#pdf('/g/steinmetz/project/TSES/mouse/run/5Seq_2013-10-08-C2GY2ACXX/performance/PCR_amplification_cumulative.pdf')
par(mfrow=c(length(myFiles)/2,2))
for( f in myFiles) {
        myT = read.delim(paste(inDir,f,sep=''))
        plot(ecdf(myT$count), pch=18, col="#00000050", xlim=c(0,100), xlab="Count per molecule (amplification)", ylab="", main=paste(strsplit(f, "_")[[1]][1], "PCR amplification"))
}

dev.off()

