---
title: "Plot overlap of positions in murine datasets"
author: "Léonie Strömich"
date: "August 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Plotting of overlap of postions in internal and Fantom5 mouse ESC data. 

Script runs on murine data.

## Prerequisites
#### Load libraries

```{r libraries, message=FALSE}
library(plyr)
library(data.table)
library(ggplot2)
library(LSD)

```

#### Read in data 

```{r read in, eval = TRUE}
##read in list of TSS in internal or Fantom5 datasets

dat_internal <- read.table("/home/stroemic/hiwi_16/analysis/lars_perl/mouse/all_internal.isoforms.csv", sep=",", header = TRUE)
dat_fantom <- read.table("/home/stroemic/hiwi_16/analysis/lars_perl/mouse/all_fantoms.isoforms.csv", sep=",", header = TRUE)

```

## Analysis

Pre-processing

```{r pre_processing, eval=TRUE}
total <- merge(dat_internal, dat_fantom, by=c("geneID","Position"), all=TRUE)
total <- subset(total, select = -c(ReadCount.x, PosFromAnno.x, Class.x, ReadCount.y, PosFromAnno.y, Class.y))
total <- plyr::rename(total,c("BarcodeCount.x"="CountInternal","BarcodeCount.y"="CountFantom"))

```


### Plotting three plot classes:


```{r plot1, eval= TRUE}
#pdf("/home/stroemic/hiwi_16/analysis/lars_perl/mouse/plots/Counts_per_position.pdf")
heatscatter(total$CountInternal, total$CountFantom, log = "xy", 
            main = "Counts per position",
            xlab = "Count internal data",
            ylab = "Count Fantom5 data")

#dev.off()
```


